sudo: required
services:
  - docker
before_install:
  - docker build -t docker-vue -f Dockerfile.dev .
script:
  - docker run docker-vue npm run test:unit
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-vue"
  env: "Dockervue-env"
  bucket_name: "elasticbeanstalk-ap-south-1-226242765231"
  bucket_path: "docker-vue"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECREAT_KEY